from reportlab.pdfgen.canvas import Canvas

from generator.config import SheetConfig
from generator.helpers import get_string_center
from generator.layout import LayoutEngine


class BubbleSheetDrawer:
    def __init__(self, canvas: Canvas, config: SheetConfig):
        self.canvas = canvas
        self.config = config
        self.layout = LayoutEngine(config)

    def draw_marker(self, x: float, y: float, size: float) -> None:
        self.canvas.setFillColorRGB(0, 0, 0)
        self.canvas.rect(x, y, size, size, fill=1, stroke=0)

    def draw_corner_markers(self, marker_positions: dict[str, tuple[float, float]]) -> None:
        for x, y in marker_positions.values():
            self.draw_marker(x, y, self.config.marker_size)

    def draw_printable_area_box(self, page_width: float, page_height: float) -> None:
        hard_margin_pt = self.config.printer_hard_margin_mm * 72.0 / 25.4
        printable_x = hard_margin_pt
        printable_y = hard_margin_pt
        printable_width = max(0.0, page_width - (2 * hard_margin_pt))
        printable_height = max(0.0, page_height - (2 * hard_margin_pt))

        self.canvas.saveState()
        self.canvas.setStrokeColorRGB(1, 0, 0)
        self.canvas.setDash(6, 3)
        self.canvas.rect(printable_x, printable_y, printable_width, printable_height, stroke=1, fill=0)
        self.canvas.setDash()
        self.canvas.setFont("Helvetica", 8)
        self.canvas.drawString(
            printable_x + 4,
            printable_y + printable_height - 10,
            f"DEBUG: PRINTER PRINTABLE AREA ({self.config.printer_hard_margin_mm:.2f} mm hard margin)",
        )
        self.canvas.restoreState()

    def draw_header(self, page_width: float, page_height: float) -> None:
        top_y = page_height - self.config.margin_y

        self.canvas.setFont("Helvetica-Bold", 18)
        self.canvas.drawString(self.config.margin_x, top_y - 40, self.config.title)

        self.canvas.setFont("Helvetica", 12)
        self.canvas.drawString(self.config.margin_x, top_y - 75, "Name: ________________________")
        student_id_box = self.draw_student_id_area(page_width, page_height)

        line_y = top_y - self.config.header_height
        line_start_x = self.config.margin_x
        line_end_x = page_width - self.config.margin_x

        if student_id_box is not None and student_id_box["bottom"] <= line_y <= student_id_box["top"]:
            line_end_x = min(line_end_x, student_id_box["left"] - 8)

        if line_end_x > line_start_x:
            self.canvas.line(line_start_x, line_y, line_end_x, line_y)

    def draw_footer(self) -> None:
        self.canvas.setFont("Helvetica-Oblique", 9)
        self.canvas.drawString(
            self.config.margin_x + 20,
            self.config.margin_y,
            "Generated by OptiMark v1.0 - https://github.com/canokan917/optimark",
        )

    def draw_bubble(self, x: float, y: float, label: str) -> None:
        self.canvas.circle(x, y, self.config.bubble_radius, stroke=1, fill=0)
        self.canvas.setFont("Helvetica", 9)
        _, center_y = get_string_center(label, "Helvetica", 9)
        self.canvas.drawCentredString(x, y - center_y, label)

    def draw_question_row(self, question_no: int, x: float, y: float, choice_center_step: float) -> None:
        self.canvas.setFont("Helvetica", 11)
        self.canvas.drawString(x, y - 4, f"{question_no:02d}.")

        bubble_start_x = (
            x
            + self.config.question_label_width
            + self.config.question_to_bubble_gap
            + self.config.bubble_radius
        )

        for idx, choice in enumerate(self.config.choices):
            bubble_x = bubble_start_x + idx * choice_center_step
            self.draw_bubble(bubble_x, y, choice)

    def draw_student_id_area(self, page_width: float, page_height: float):
        box = self.layout.get_student_id_box(page_width, page_height)
        if box is None:
            return None

        digits = [1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
        grid_top_y = box["top"]
        grid_start_x = box["left"]
        col_width = box["col_width"]
        write_box_height = box["write_box_height"]
        bubble_radius = self.config.bubble_radius
        bubble_step = box["bubble_step"]
        first_bubble_y = box["first_bubble_y"]
        col_bottom_y = box["bottom"]
        col_height = box["height"]

        self.canvas.setFont("Helvetica-Bold", 10)
        self.canvas.drawString(grid_start_x, grid_top_y + 8, "Student ID")

        for col in range(self.config.max_student_ID_len):
            col_left_x = grid_start_x + col * col_width
            col_center_x = col_left_x + (col_width / 2)

            # One boxed lane per ID digit: top write cell + OMR bubbles underneath.
            self.canvas.rect(col_left_x, col_bottom_y, col_width, col_height, stroke=1, fill=0)
            self.canvas.line(col_left_x, grid_top_y - write_box_height, col_left_x + col_width, grid_top_y - write_box_height)

            for row_idx, digit in enumerate(digits):
                bubble_y = first_bubble_y - row_idx * bubble_step
                self.canvas.circle(col_center_x, bubble_y, bubble_radius, stroke=1, fill=0)

                self.canvas.setFont("Helvetica", 10)
                _, center_y = get_string_center(str(digit), "Helvetica", 10)
                self.canvas.drawCentredString(col_center_x, bubble_y - center_y, str(digit))

        return box
